### PR TITLE
Open Telemetry instrumentation in Startup.cs file

### PR DESCRIPTION
**Pull request by kamleshplayerzero**
This change is [Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19)

### CODE REVIEW

**Review by sepatel — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19)* status: all files reviewed, 2 unresolved discussions (waiting on @AnimeshKoratana and @kamleshplayerzero)

___
*[`ProgramNStartup/README.md` line 85 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19#-O9VYcQ32N52woKhh3LL:-O9VYcQ447ERoXhy0h5Q:b61ohkk) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet-framework/blob/99f4fab03165aa44b54f9bf36b04e78bee2ffc12/ProgramNStartup/README.md#L85)):*
> ```Markdown
>                 .WithMetrics(metrics => metrics
>                     .AddMeter(serviceName)
>                     .AddMeter("System.Net.NameResolution")
> ```

Actually can you remove this one. We don't really want DNS metrics even once we do get that put together later.
___
*[`ProgramNStartup/Startup.cs` line 74 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19#-O9VYldqEyObv1upVdTH:-O9VYldqEyObv1upVdTI:b-u16e2g) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet-framework/blob/99f4fab03165aa44b54f9bf36b04e78bee2ffc12/ProgramNStartup/Startup.cs#L74)):*
> ```Smalltalk
>                 .WithMetrics(metrics => metrics
>                     .AddMeter(serviceName)
>                     .AddMeter("System.Net.NameResolution")
> ```

Same note as above

**Review by kamleshplayerzero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @AnimeshKoratana and @sepatel)

___
*[`ProgramNStartup/README.md` line 85 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19#-O9VYcQ32N52woKhh3LL:-O9VZ5Lf0zVCYRCbm90C:bb6un1j) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet-framework/blob/99f4fab03165aa44b54f9bf36b04e78bee2ffc12/ProgramNStartup/README.md#L85)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Actually can you remove this one. We don't really want DNS metrics even once we do get that put together later.
</blockquote></details>

Done

**Review by kamleshplayerzero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @AnimeshKoratana and @sepatel)

___
*[`ProgramNStartup/Startup.cs` line 74 at r1](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19#-O9VYldqEyObv1upVdTH:-O9VZROnAXWCb8doaaG2:b-896fix) ([raw file](https://github.com/goplayerzero/open-telemetry-dotnet-framework/blob/99f4fab03165aa44b54f9bf36b04e78bee2ffc12/ProgramNStartup/Startup.cs#L74)):*
<details><summary><i>Previously, sepatel (Ryba) wrote…</i></summary><blockquote>

Same note as above
</blockquote></details>

Done.

**Review by sepatel — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/goplayerzero/open-telemetry-dotnet-framework/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AnimeshKoratana)

**Pull request merged**
